name: Join + Matrix

on:
  push:

jobs:
  performance-test:
    strategy:
      matrix:
        threads: [10, 50, 100]

    runs-on: ubuntu-latest

    steps:
      - name: Show configuration
        run: |
          echo "Current threads: ${{ matrix.threads }}"
          echo "Load levels: ${{ join(fromJSON('[10,50,100]'), ', ') }}"
